### PR TITLE
Adding the explicit check for None allows us to use 0. as a valid val…

### PR DESCRIPTION
**Pull request by joseph-ruskiewicz**
…ue for coef or offset.

### CODE REVIEW

**Comment by ymwdalex** [comment]
@twobitunicorn thanks for the PR. It looks good to me!

You also submitted another 2 PR just minutes ago. It looks like they have the same change as this one.

Can I just merge this one and discard other two?

**Comment by ymwdalex** [comment]
> @twobitunicorn thanks for the PR. It looks good to me!
> 
> You also submitted another 2 PR just minutes ago. It looks like they have the same change as this one.
> 
> Can I just merge this one and discard other two?

Or I can merge other two PR since they have better title and descriptions.

**Comment by joseph-ruskiewicz** [comment]
@ymwdalex Absolutely.  Apologies.  I am not sure how the other two PRs got pulled into this one.  But, ya, i'll delete the other two and we can pull this one.  appreciated.

**Comment by joseph-ruskiewicz** [comment]
@ymwdalex Just realized this came from my master.  which I must have already pulled the other two in.  I have closed them so feel free to pull this one in.

**Review by ymwdalex — APPROVED** [review]
LGTM! Thanks @twobitunicorn

**Pull request merged**
